[package]
name = "fluvio"
version = "1.0.0"

[addresses]
fluvio = "0xC809333033602FEA438A4917DD1890D0F3EB8851"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "main" }
